sudo: required
services:
  - docker


before_install:
  - docker build -t nicopanjaitan0607-ardi/docker-react -f Dockerfile.dev .




script:
  - docker run -e CI=true nicopanjaitan0607-ardi/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_patch: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
